CUSTOM_NAME=meowminer
CUSTOM_VERSION=@VERSION@
CUSTOM_BUILD=1
CUSTOM_ALGO=multicoin
CUSTOM_MINERBIN=MeowMiner
CUSTOM_CONFIG_FILENAME=/hive/miners/custom/meowminer/meowminer.conf
CUSTOM_LOG_BASENAME=/var/log/miner/meowminer/meowminer
WEB_PORT=4051
